### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by Foskas** [nomi9995/react-native-keys#2]
Hi,

I was able to add the lib to my project and make it work on Android.

On iOS I don't have any errors but I can't see the secure/public keys from my keys.json file. What I can see is the keys that you added by default on the generatedDotEnvFile.

My logfile inclues: `env: node: No such file or directory`

Is anyone aware of what this issue is or the route cause ? I can't find a solution for it. I did follow all the spects on README but I can't make it work.

Thanks!

**Comment by Foskas** [comment]
FIXED: The issue was created by using NVM. Xcode was not able to find node

**Comment by YangJonghun** [comment]
@numandev1 
I hope you add any guide for user who used Node.js version manager (nvm or fnm ...)
I think a lot of RN developers are not familiar with native ecosystem.
So I suggest to add Pre-actions script guide within document (like [Sentry SDK guide](https://docs.sentry.io/clients/react-native/manual-setup/#using-node-with-nvm-or-notion))

```
# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Set up the fnm node version manager if present
if [[ -s "$HOME/.fnm/fnm" ]]; then
  eval "`$HOME/.fnm/fnm env --multi`"
fi

# Trying notion
if [ -z "$NODE_BINARY" ]; then
if [[ -s "$HOME/.notion/bin/node" ]]; then
export NODE_BINARY="$HOME/.notion/bin/node"
fi
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

$NODE_BINARY "${SRCROOT}/../node_modules/react-native-keys/keysIOS.js"
```
